---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ebs-eu-west-1a
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-1a
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ebs-eu-west-1b
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-1b
