version: '2'
services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    ports:
    - "5000:5000"
    environment:
    - REGISTRY_LOG_LEVEL=debug
    - REGISTRY_STORAGE_DELETE_ENABLED=true
    - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt
    - REGISTRY_HTTP_TLS_KEY=/certs/server.key
    - REGISTRY_AUTH_TOKEN_REALM=https://168.124.129.35/v2/token
    - REGISTRY_AUTH_TOKEN_SERVICE=168.124.129.35:5000
    - REGISTRY_AUTH_TOKEN_ISSUER=168.124.129.35
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/etc/nginx/ssl/server.crt
    - REGISTRY_NOTIFICATIONS_ENDPOINTS_NAME=portus
    - REGISTRY_NOTIFICATIONS_ENDPOINTS_URL=https://168.124.129.35/v2/webhooks/events
    - REGISTRY_NOTIFICATIONS_ENDPOINTS_TIMEOUT=500
    - REGISTRY_NOTIFICATIONS_ENDPOINTS_THRESHOLD=5
    - REGISTRY_NOTIFICATIONS_ENDPOINTS_BACKOFF=1
    volumes:
    - /root/portus-compose/ssl/server.crt:/etc/nginx/ssl/server.crt
    - /root/portus-compose/ssl:/certs
    - /tmp/data:/var/lib/registry
  portus-mysql:
    image: mysql
    restart: always
    container_name: portus-mysql
    environment:
    - MYSQL_DATABASE=portus
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=portus
    - MYSQL_PASSWORD=dbpassword
    volumes:
    - /tmp/portus:/var/lib/mysql
  portus:
    image: sshipway/portus:2.0.4
    restart: always
    container_name: portus
    links:
    - registry:registry
    - portus-mysql:portus-mysql
    environment:
    - PORTUS_MACHINE_FQDN=168.124.129.35
    - PORTUS_LDAP_ENABLED=true
    - PORTUS_LDAP_HOSTNAME=HOSTNAME
    - PORTUS_LDAP_PORT=389
    - PORTUS_LDAP_METHOD=plain
    - PORTUS_LDAP_BASE=BASE
    - PORTUS_LDAP_UID=SAMAccountName
    - PORTUS_LDAP_AUTHENTICATION_ENABLED=true
    - PORTUS_LDAP_AUTHENTICATION_BIND_DN=BIND
    - PORTUS_LDAP_AUTHENTICATION_PASSWORD=PWD
    - PORTUS_LDAP_GUESS_EMAIL_ENABLED=true
    - PORTUS_LDAP_GUESS_EMAIL_ATTR=mail
    - PORTUS_PRODUCTION_HOST=portus-mysql
    - PORTUS_PRODUCTION_DATABASE=portus
    - PORTUS_PRODUCTION_USERNAME=portus
    - PORTUS_PRODUCTION_PASSWORD=dbpassword
    - PORTUS_KEY_PATH=/certs/server.key
    - PORTUS_PASSWORD="password"
    - PORTUS_SECRET_KEY_BASE="apikeybase"
    - REGISTRY_USE_SSL=true
    - PORTUS_CHECK_SSL_USAGE_ENABLED=true
    - LOG_LEVEL=debug
    volumes:
    - /tmp/proxy:/etc/nginx/conf.d
    - /root/portus-compose/ssl:/certs
    - /root/portus-compose/ssl/ca.pem:/usr/local/share/ca-certificates/ca.crt
  portus-ssl:
    image: nginx
    restart: always
    container_name: portus-ssl
    ports:
    - 443:443
    links:
    - portus:portus
    volumes:
    - /tmp/proxy:/etc/nginx/conf.d
    - /root/portus-compose/ssl:/etc/nginx/certs
    environment:
    - NGINX_CERT_FILE=/etc/nginx/certs/server.crt
    - NGINX_KEY_FILE=/etc/nginx/certs/server.key
    - NGINX_DOMAIN=168.124.129.35