apiVersion: v1
kind: Service
metadata:
    name: ghost
    labels:
        app: ghost
spec:
    selector:
        app: ghost
    ports:
        - port: 80
          targetPort: ghost-port
    type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: ghost
        image: ghost
        command:
          - ping
        args:
          - 8.8.8.8
        ports:
        - name: ghost-port
          containerPort: 2368
        volumeMounts:
        - name: test
          mountPath: /var/lib/ghost
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
        - name: test
          flexVolume:
            driver: "coreos.com/torus"
            fsType: "ext4"
            options:
              volume: "test"
              etcd: "10.3.0.100:2379"
