---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "DEBUG"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [kubernetes]
    [web]
    address = ":8080"
    [acme]
    caServer = "https://acme-staging.api.letsencrypt.org/directory"
    email = "lefevre.kevin@gmail.com"
    storage = "traefik/acme/account"
    entryPoint = "https"
    onHostRule = true
    [[acme.domains]]
    main = "archifleks.xyz"
