apiVersion: v1
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
      [entryPoints.https.tls]
    [web]
    [kubernetes]
    [acme]
      email = "lefevre.kevin@gmail.com"
      storage = "/acme/acme.json"
      entryPoint = "https"
    [acme.dnsChallenge]
      provider = "route53"
      delayBeforeCheck = 0
    [[acme.domains]]
      main = "*.archifleks.net"
      sans = ["archifleks.net"]
kind: ConfigMap
metadata:
  name: traefik-conf
