version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd
    ports:
      - "4001:4001"
      - "2379:2379"
      - "2380:2380"
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
    command: etcd -name etcd0 -advertise-client-urls http://127.0.0.1:2379,http://127.0.0.1:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls http://127.0.0.1:2380 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster-1 -initial-cluster etcd0=http://127.0.0.1:2380 -initial-cluster-state new
  discovery_etcd:
    image: quay.io/coreos/discovery.etcd.io
    container_name: discovery_etcd
    ports:
      - "8087:8087"
    environment:
      - DISC_ETCD=http://etcd:2379
      - DISC_HOST=http://tamachine.io
